### ISSUE TITLE
Inastallation and first use

### ISSUE THREAD

**Issue by SweatyHands** [efrecon/influx-backup#8]
Hello,

I am a complete newbie when it comes to the world of influx and using linux server.

I want to use this tool to make regular backups of my database.

However I am already struggling to get the backup.tcl running.

I just copied all the files to the ubntu server, but how and where do I install it?

I am sorry for my stupid question, but I hope someone can give me short answer and help?

**Comment by efrecon** [comment]
Make sure you have an installation of TCL. Most systems have it. Move the script to a location in your $PATH, if you want to make it accessible for all users, maybe /usr/local/bin? Make sure the script has the exec bits set.
